### ISSUE TITLE
FileScan from URL

### ISSUE THREAD

**Issue by Jcambass** [Genbox/VirusTotal.NET#14]
# Provide a function to scan a file from a URL.
It would be nice if there was a way to provide a URL and have the associated file scanned.
Just like if you Scan an URL via [VirusTotal.com](http://virustotal.com) and then klick on:
> Go to downloaded file analysis

![unbenannt](https://cloud.githubusercontent.com/assets/3436381/9872790/eef847ca-5b9b-11e5-9999-f4e84c57e431.png)

This feature would be very usefull for having a FileScan from an exe from some Webpage before actually downloading it.

If there is alreaedy a way to do this please let me know!

**Comment by Genbox** [comment]
Thanks for suggesting this feature, however, I don't think it is an API feature. This project is just a simple implementation of [the API](https://www.virustotal.com/en/documentation/public-api/) with some extra help for convenience sake.

Had VT implemented a function to scan the file at an URL in their API, I would implement it to keep it updated, but this seems to be outside of the API realm.

**Comment by Jcambass** [comment]
Thank you for your time ynway :)  Just for completion I'll post a comment if I find a comfortable way to scan a file from URL.

**Comment by Jcambass** [comment]
I contacted the VT-Support, actually there is a Way to do it.. but It's only avaiable in the paid API...

Quote from "karl Hiramoto":

> HI Joel,
I was mistaken, this piece of data is only available on our paid private API when you use the "allinfo=1" parameter
https://www.virustotal.com/en/documentation/private-api/#url-report
You would see in the response a "filescan_permaid"
https://www.virustotal.com/vtapi/v2/url/report?apikey=YOUR_PRIVATE_API_KEY&resource=http://upload.siamza.com/download.php?id=2296595&allinfo=1
"additional_info": {
"BitDefender domain info": "This URL domain/host was seen to host badware at some point in time",
"Response content SHA-256": "b0490431cda3df5588dad6e8d269ed9d79baa49aef4a5548b881cff96c7af519",
"resolution": "27.254.144.160",
"URL after redirects": "http://upload.siamza.com/download.php?id=2296595",
"resolution_country": "TH",
"Websense ThreatSeeker category": "malicious web sites",
"filescan_permaid": "b0490431cda3df5588dad6e8d269ed9d79baa49aef4a5548b881cff96c7af519-1444108498",
"Response code": 200,
"Response headers": {
"content-length": "382592",
"content-disposition": "attachment; filename=TalesRunner Thailand Free.rar",
"x-powered-by": "PHP/5.5.25",
"server": "Apache",
"connection": "close",
"cache-control": "private",
"date": "Tue, 06 Oct 2015 05:14:54 GMT",
"content-type": "application/octet-stream"
},
You can then use the file/report API call to fetch the file scan report
