### ISSUE TITLE
Support rate limiting

### ISSUE THREAD

**Issue by mganss** [Genbox/VirusTotal.Net#16]
- Make number of requests configurable
- Should be optional (0 = unlimited?)
- Use `Task.Delay()` for async (see #15)

I know this is likely not easily done, since the rate limit is not based on the number of HTTP requests. Here's what the VirusTotal docs say:

> When considering API quotas, an API request is not equivalent to an HTTP request. This concept designates a single item lookup in the VirusTotal dataset. Therefore, if you were to make one single batch HTTP request asking for 10 hashes, that would count as 10 API requests. Similar counting takes place for other items such as URLs, domains or IP addresses.

**Comment by Genbox** [comment]
The API is rate limited by HTTP requests. Taken from the documentation: "[The API] is limited to at most 4 requests of any nature in any given 1 minute time frame".

Individual API requests (not HTTP requests) are used for the paid version of the API where you pay for each resource you scan/retrieve.

It is up to the implementation of the API library to react on HTTP request rate limits. A RateLimitException is thrown once the limit is hit, but generally you should just keep to 4 requests within a given minute.

**Comment by mganss** [comment]
I believe the excerpt from the documentation I quoted applies to the public API as well. It is shown on the "My API key" page.

Anyhow, IMO it would be a nice feature if the library (optionally) delayed requests so that the rate limit is automatically honored and the client wouldn't have to worry about it.

**Comment by Genbox** [comment]
It is indeed, but it is not counted as a factor in the rate limiting. I use the API for scanning malware samples and check reports on 250 files at the time, the only limit I've ever hit is the 4 requests pr. min. pr. IP. Note that the documentation is also not in sync with the actual implementation. I've tried to address this with the VT team, but they didn't change anything.

As for the rate limiting; different applications have different strategies for handling rate limiting. I'd like for the library to be just about the VT API and make it easily consumable. It is not a fire and forget library that handles everything for you, it is just a dumb API implementation. Stuff like rate limiting, chunking of resources, in-memory caching and so on should be done in a client instead.

**Comment by mganss** [comment]
> It is indeed, but it is not counted as a factor in the rate limiting.

Good to know :wink:

**Comment by Genbox** [comment]
There are future plans for supporting the private VT API, and as such, this issue can be fixed when doing the simple queue based batching. Reopening.

**Comment by Genbox** [comment]
VirusTotal changed their license and now discourage automation as it would harm the antivirus community (their words). Since automatic batching is an automation feature, I'm going to close it. People should be able to easily implement their own batching.
