### ISSUE TITLE
DomainReport WhoIsDateTime Throws Exception

### ISSUE THREAD

**Issue by keithjjones** [Genbox/VirusTotal.NET#19]
If you take one domain report and try to copy the WhoisDateTime to the other, it throws an exception.  A good example of this is using the domain fenggui.f3322.net.  

The use of the function to calculate this field from WhoIsTimestamp may be the culprit.  If the WhoIsTimestamp field is not a valid number for calculation, the exception may propagate from WhoisDateTime.  It is unclear to me exactly where the problem is, but I'm pretty sure it is the use of functions that may throw an exception.

I see this happen when WhoIsTimestamp is null, especially.  There should be a check for this condition somewhere.

**Comment by keithjjones** [comment]
I proposed a fix in pull request #20.

**Comment by Genbox** [comment]
I've fixed the bugs reported and added you as a contributor.
