### ISSUE TITLE
Support Large File Uploads

### ISSUE THREAD

**Issue by ferventcoder** [Genbox/VirusTotal.Net#24]
I didn't see this implemented in the VT Private API PR (#18), so I thought I would contribute back some working code.

**Comment by Green7** [comment]
Do you have plans for handling large file uploads ?

**Comment by Genbox** [comment]
I can't include features I can't test to ensure it works correctly. I need a private VT API key to test this kind of functionality, and even after negotiations with VT, they don't want to sell me one.

**Comment by Green7** [comment]
Large file uploads is available also in public API. 
All you need to do is write an email with request: https://support.virustotal.com/hc/en-us/requests/new
I did it and within a hour my account was enabled to send large files.

**Comment by Genbox** [comment]
Thanks. I will send them a request and try.

**Comment by Genbox** [comment]
I've asked VT to enable this feature for my API key to support your request. I'm waiting for a response.

**Comment by Green7** [comment]
It works. Good job !
