### ISSUE TITLE
"The request was aborted: The request was canceled". ScanFile

### ISSUE THREAD

**Issue by RainbowJeZ** [Genbox/VirusTotal.NET#26]
Hi,

Sorry if this is the wrong way to contact you.

When using the client project, I remove the if statement to force the ScanFile to take place. The request returns the response: The request was aborted: The request was canceled. I have successfully used GetFileReport and RescanFiles. 

The exception is thrown in the GetResults method, response.ErrorException != null.

Let me know if you need any more info.

Thanks and great work I learnt a lot reading your code.

Rain

**Comment by garet999** [comment]
Hello,

I appear to have run into the same issue. I ran the application, but it just closes the stream before completing it appears. Is there a potential fix on the way perhaps? I would love to use this piece of software in my project.

Thanks in advance, and for your contribution.

- Jeroen

**Comment by zhutao233** [comment]
“Reverted RestSharp back to 105.1.0 due to bug”
First make sure your RestSharp version @RainbowJeZ

**Comment by RainbowJeZ** [comment]
Worked for me. Thank you
