### ISSUE TITLE
Url scan

### ISSUE THREAD

**Issue by pingpongbc** [Genbox/VirusTotal.NET#30]
Is there anyway i can automatically put the url in?
![url](https://cloud.githubusercontent.com/assets/24495462/22596848/29381cba-ea68-11e6-9da4-156a637d40fc.jpg)

**Comment by Genbox** [comment]
On line 55 in the class you have open, the URL you have in the screenshot is being scanned.

**Comment by pingpongbc** [comment]
Yes yes i know i mean like any way i can automatically put the url through a text file or something. Instead of hardcoding it?

**Comment by pingpongbc** [comment]
btw thank you for replying so promptly :D

**Comment by Genbox** [comment]
This is more a general question about C# than this library. However, I'll give a quick example anyway:
```csharp
static void Main(string[] args)
{
    RunExample().Wait();

    Console.WriteLine("Press a key to continue");
    Console.ReadLine();
}

private static async Task RunExample()
{
    //Read all the urls
    string[] urlArray = File.ReadAllLines("FileWithUrls.txt");

    //Create VirusTotal API. Remember to set the API key
    VirusTotal virusTotal = new VirusTotal("YOUR API KEY HERE");
    virusTotal.UseTLS = false;

    //We scan all the urls in the urlArray
    List<UrlScanResult> scanResults = await virusTotal.ScanUrls(urlArray);

    //Print out all the results
    foreach (UrlScanResult result in scanResults)
    {
        Console.WriteLine(result.Url + " " +  result.ScanDate);
    }
}
```

**Comment by Genbox** [comment]
There is a bug related to ScanURLs() - Update to version 1.5.1 to fix it.

**Comment by pingpongbc** [comment]
Thank you for ur reply. May I Noe what is application u like visual studio console application or windows forms or wpf application

**Comment by pingpongbc** [comment]
Haha okay I know it's a class library just wanna ask another question is: is it possible to make it to an executable file :)

**Comment by pingpongbc** [comment]
Such that I can call this virustotal automatically

**Comment by Genbox** [comment]
You can download the example included in the VirusTotal.NET package and replace the code, with the code i posted above. In .NET core, you will get a DLL file, which you can run just like an EXE file, by calling `dotnet <InsertDllNameHere>`. I'm closing this issue, as it is not related to this project.
