### ISSUE TITLE
Possible Bug deserializing Json

### ISSUE THREAD

**Issue by ikren80** [Genbox/VirusTotal.Net#31]
Hi,

I get an exception when I try to obtain the info from the second domain:

> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'

It seems that the JSON does not always have the PropertyName: 'whois_timestamp'. 

Code to reproduce the issue (the exception arise in the second domain. I leave the first one for test purpouses):
```
public static void Main(string[] args)
{
    DomainReport dr = Test("google.com").Result;
    DomainReport dr2 = Test("ak.imgfarm.com").Result;
}

public static async Task<DomainReport> Test(string dom)
{
     VirusTotal VT = new VirusTotal("API_KEY");
     DomainReport dr = await VT.GetDomainReport(dom);
     return dr;
}
```
Code I used to see whether the field 'whois_timestamp' is always available.

```
private async Task<T> GetResult<T>(string url, HttpMethod method, HttpContent content)
{
    HttpResponseMessage response = await SendRequest<T>(url, method, content);

    using (Stream responseStream = await response.Content.ReadAsStreamAsync())
    using (StreamReader sr = new StreamReader(responseStream, Encoding.UTF8))
    using (JsonTextReader jsonTextReader = new JsonTextReader(sr))
    {
        jsonTextReader.CloseInput = false;

        //my inserted test code
        string jsonTest = "";

        while (jsonTextReader.Read())
        {
            if (jsonTextReader.Value != null)
            {
                jsonTest += jsonTextReader.TokenType;
                jsonTest += " | ";
                jsonTest += jsonTextReader.Value;
                jsonTest += " ; ";

            }
            else
            {
                jsonTest += jsonTextReader.TokenType;
                jsonTest += " |\n ";
            }
        }
                
        File.WriteAllText("d:\\jsontestfile.txt", jsonTest);
        //end of my inserted test code

        return _serializer.Deserialize<T>(jsonTextReader);
    }
}
```
Thanks in advance!

Regards.

**Comment by Genbox** [comment]
Thanks for reporting this.

This issue happens from time to time since everything in this library is based on observations of the VirusTotal protocol. They don't have any documentation on what fields are available, and what types they are, so I pretty much guessed.

I will fix this momentarily.

**Comment by Genbox** [comment]
I'm unable to reproduce it for whois_timestamp, but the same error happened in Resolution.LastResolved. I've added nullhandling to both.
