### ISSUE TITLE
Possible JSON bug

### ISSUE THREAD

**Issue by anovik** [Genbox/VirusTotal.Net#32]
Hi,

It seems there is one more bug regarding JSON serialization, could you please have a look and fix if possible:

> Error Message: Error setting value to 'Update' on 'VirusTotalNET.Objects.ScanEngine'.

> Stack Trace: at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> 
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> 
> at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
> 
> at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
> 
> at VirusTotalNET.VirusTotal.<GetResult>d__76`1.MoveNext()

**Comment by Genbox** [comment]
Can you provide the query you made that caused this?

**Comment by anovik** [comment]
Thanks for your reply. It happens while executing:

> FileReport report = await _virusTotal.GetFileReport(fileInfo);

But I can reproduce it only with some of the files (but in 100% cases). With other files it works perfectly (also in 100% cases). 

Please let me know if you need more information.

**Comment by Genbox** [comment]
Can you get me a hash of one of the files where it fails?
I've run GetFileReport on thousands of files now, but I can't seem to reproduce it.

**Comment by anovik** [comment]
I had it all the time with file with SHA-1 = 0b80fcb7d3e00c159f4d195b22aa75b8b1d0a9a5. While it was it queue it gave the exception above. Since it was processed (about 20 hours ago, information from here https://www.virustotal.com/ru/file/90ba9f048d684873441011aaa3882b940646ad0e6e36a64e76306d5f36664673/analysis/), it is ok now. How can we solve that? Can we find at least any workaround?

**Comment by Genbox** [comment]
The VirusTotal API is unstable in the sense that it constantly returns invalid data. The API impose some constraints on the data, like it expects a date to be in a certain format, which is why it crashes sometimes when VT sends us invalid data. 

I think there are a couple of ways to help with this.
1. I can throw an exception in the custom datetime parser that shows the data it received.
2. I can provide a debug setting that dumps the raw JSON to a file in the temp folder of the system.

That should make it easier to determine what goes wrong when we get invalid data.

**Comment by anovik** [comment]
Probably custom exception could help if we know what to expect and do with it (ignore, try to send later, etc.)

**Comment by Genbox** [comment]
You are right. I'll change it to a custom exception.

**Comment by Genbox** [comment]
I've made some checks that should help. You can also set VirusTotal.DumpRawJSON to true when you get the error again. If you manage to get som JSON that crashes the API, please send it to me.

Thanks for reporting the issue - I'm going to close this one, and if you get an error again, please open up a new one.
