### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by schwarrior** [Genbox/VirusTotal.Net#35]
I needed a version of this API client that runs pre .NET Core - specifically on .NET Framework 4.5.1. So I forked the repo and rebuilt the solution under .NET 4.5.1. It was easy and it works great; just like the parent repo. Find it here https://github.com/schwarrior/VirusTotal.Net.
If you would like to have this code as an official branch in here in this repo, cool, I am happy to contribute.

**Comment by Genbox** [comment]
You should be able to reference this library directly as it already targets .NET Framework 4.5.
See targets in: https://github.com/Genbox/VirusTotal.Net/blob/master/VirusTotal.NET/VirusTotal.NET.csproj

What kind of issues did you have?

**Comment by schwarrior** [comment]
I was unable to open the solution in Visual Studio 2015. I had to use Visual Studio 2017. I assumed this meant it was a .Net Core project targeting something above 4.5. But you are right, on closer inspection, its plain old (non Core) 4.5. So I guess what I pushed to https://github.com/schwarrior/VirusTotal.Net was a version of the project that works in Visual Studio 2015.

**Comment by schwarrior** [comment]
![image](https://user-images.githubusercontent.com/8260511/28464924-1586019e-6df5-11e7-8969-d3e8dab9a134.png)

**Comment by schwarrior** [comment]
Above image is the error when attempting to open the sln or a proj file from https://github.com/Genbox/VirusTotal.Net in Visual Studio 2015

**Comment by Genbox** [comment]
Looks like it. I'm not sure if there is VS2015 support in .NET Core. The dotnet CLI application should work no matter what version of VS you are using, so you could always build it in the CLI and just reference the resulting assembly.

I'm closing this issue as it seems resolved.
