### ISSUE TITLE
Contributor Request

### ISSUE THREAD

**Issue by sdunnin** [Genbox/VirusTotal.Net#36]
Hi,

I can't find any mechanism to request access to this repository as a contributor so I figured that I would just create an issue. 

I had a need to serialize a FileReport and ran into the problem of YearMonthDayConverter.WriteJson not being implemented. I implemented that method and would like to submit pull request for consideration.

Thanks!

**Comment by Genbox** [comment]
If you fork the project and implement the solution in your fork, then you can create a merge request between your version and this project, which is how you contribute.

**Comment by sdunnin** [comment]
Thanks, kind of a noob here with regard to GH contributing.
