### ISSUE TITLE
Invalid date/time from VirusTotal

### ISSUE THREAD

**Issue by FusionCarcass** [Genbox/VirusTotal.Net#40]
The VirusTotal.Net project has issues handling the old date/time format that VirusTotal used in 2013 and prior (ex. Invalid date/time from VirusTotal. Tried to parse: 20131008122812). I have included a snippet of the json below.

{"scans": {"Bkav": {"detected": false, "version": "1.3.0.4246", "result": null, "update": "20131008122812"}, "MicroWorld-eScan": {"detected": true, "version": "12.0.250.0", "result": "Win32.Expiro.BD", "update": "20131009020734"}, "nProtect": {"detected": true, "version": "2013-10-08.04", "result": "Win32.Expiro.BD", "update": "20131008105903"}, "CAT-QuickHeal": {"detected": true, "version": "12.00", "result": "W32.Expiro.AX", "update": "20131008074150"}, "McAfee": {"detected": true, "version": "6.0.4.564", "result": "W32/Expiro.gen.n", "update": "20131009024415"}, "Malwarebytes": {"detected": false, "version": "1.75.0001", "result": null, "update": "20131009013332"}, "TheHacker": {"detected": false, "version": null, "result": null, "update": "20131007194026"}, "K7GW": {"detected": true, "version": "12.7.0.14", "result": "Virus", "update": "20131008182912"}, "K7AntiVirus": {"detected": true, "version": "9.173.9818", "result": "Virus", "update": "20131008181418"}, "Agnitum": {"detected": false, "version": "5.5.1.3", "result": null, "update": "20131008162700"}, "F-Prot": {"detected": true, "version": "4.7.1.166", "result": "W32/Expiro.AH", "update": "20131009040050"}, "Norman": {"detected": true, "version": "7.02.06", "result": "Expiro.YG", "update": "20131008130626"}, "TotalDefense": {"detected": true, "version": "37.0.10593", "result": "Win32/Expiro.V", "update": "20131008212850"}, "TrendMicro-HouseCall": {"detected": true, "version": "9.700-1001", "result": "PE_EXPIRO.JX", "update": "20131009032410"}, "Avast": {"detected": true, "version": "8.0.1489.320", "result": "Win32:Xpiro", "update": "20131008113516"}, "ClamAV": {"detected": true, "version": "0.97.3", "result": "WIN.Virus.Expiro-9", "update": "20131009034451"}, "Kaspersky": {"detected": true, "version": "9.0.0.837", "result": "Virus.Win32.Expiro.ao", "update": "20131009024117"}, "BitDefender": {"detected": true, "version": "7.2", "result": "Win32.Expiro.BD", "update": "20131009034245"}, "NANO-Antivirus": {"detected": true, "version": "0.26.0.55366", "result": "Virus.Win32.Expiro.buroko", "update": "20131008210452"}, "SUPERAntiSpyware": {"detected": false, "version": "5.6.0.1032", "result": null, "update": "20131009021134"}, "Emsisoft": {"detected": false, "version": "3.0.0.589", "result": null, "update": "20131009034856"}, "Comodo": {"detected": true, "version": "17075", "result": "Virus.Win32.Expiro.isn", "update": "20131009022724"}, "F-Secure": {"detected": true, "version": "11.0.19100.45", "result": "Win32.Expiro.BD", "update": "20131009015730"}, "DrWeb": {"detected": true, "version": "7.00.5.06250", "result": "Win32.Expiro.58", "update": "20131009034751"}, "VIPRE": {"detected": true, "version": "22218", "result": "Virus.Win32.Expiro.gen.a (v)", "update": "20131009033945"}, "AntiVir": {"detected": true, "version": "7.11.106.104", "result": "W32/Infector.Gen8", "update": "20131008113027"}, "TrendMicro": {"detected": true, "version": "9.740-1012", "result": "PE_EXPIRO.JX", "update": "20131009025306"}, "McAfee-GW-Edition": {"detected": true, "version": "2013", "result": "W32/Expiro.gen.n", "update": "20131009024724"}, "Sophos": {"detected": true, "version": "4.93.0", "result": "W32/Expiro-H", "update": "20131008224916"}, "Jiangmin": {"detected": false, "version": "16.0.100", "result": null, "update": "20130903053935"}, "Panda": {"detected": true, "version": "10.0.3.5", "result": "W32/Expiro.gen", "update": "20131008110242"}, "Antiy-AVL": {"detected": false, "version": "2.0.3.7", "result": null, "update": "20131008113213"}, "Kingsoft": {"detected": false, "version": "2013.04.09.267", "result": null, "update": "20130829055915"}, "Microsoft": {"detected": true, "version": "1.9901", "result": "Virus:Win32/Expiro.BK", "update": "20131009024936"}, "ViRobot": {"detected": false, "version": "2011.4.7.4223", "result": null, "update": "20131008234114"}, "GData": {"detected": true, "version": "22", "result": "Win32.Expiro.BD", "update": "20131009020200"}, "Commtouch": {"detected": true, "version": "5.4.1.7", "result": "W32/Expiro.AH", "update": "20131009034625"}, "ESET-NOD32": {"detected": true, "version": "8893", "result": "Win32/Expiro.NAP", "update": "20131009020959"}, "VBA32": {"detected": true, "version": "3.12.24.3", "result": "SScope.Virus.Expiro.gen", "update": "20131008112330"}, "PCTools": {"detected": true, "version": "9.0.0.2", "result": "Malware.Xpiro", "update": "20131002161145"}, "Rising": {"detected": true, "version": "23.0.0.3 \r", "result": "Win32.Expiro.v", "update": "20131008024637"}, "Ikarus": {"detected": true, "version": "T3.1.5.4.0", "result": "Virus.Win32.Expiro", "update": "20131009020437"}, "Fortinet": {"detected": true, "version": "4", "result": "W32/Expiro.NAP", "update": "20131009035813"}, "Baidu-International": {"detected": false, "version": "3.5.1.41473", "result": null, "update": "20131008094448"}}, "scan_id": "8478dd81853cd1dabef424e3dd9b5f321714adc3d569fe54798f213b56c7b47a-1381287894", "sha1": "0fa898af7e885fffbcfab7cbdc2f3cd9751d11f0", "resource": "8478dd81853cd1dabef424e3dd9b5f321714adc3d569fe54798f213b56c7b47a", "response_code": 1, "scan_date": "2013-10-09 03:04:54", "permalink": "https://www.virustotal.com/file/8478dd81853cd1dabef424e3dd9b5f321714adc3d569fe54798f213b56c7b47a/analysis/1381287894/", "verbose_msg": "Scan finished, information embedded", "total": 44, "positives": 33, "sha256": "8478dd81853cd1dabef424e3dd9b5f321714adc3d569fe54798f213b56c7b47a", "md5": "06237229cd2116d9d11a7c7a6e668ca3"}

**Comment by FusionCarcass** [comment]
Resubmitting the sample causes VirusTotal to fix the date/time format, so I'm not sure if it is a significant issue; however, it does make handling these samples slightly more difficult for those depending upon the API.

**Comment by Genbox** [comment]
There is even half a newline in the version field for "Rising"...
